### ISSUE TITLE
automatically calculate entry_sequence_number

### ISSUE THREAD

**Issue by senny** [phuesler/payment_dta#2]
The DTA specification notes, that every record in a DTA file needs to have a unique 5-diget sequence number. I scanned the codebase and it seems that the caller of payment_dta needs to supply the sequence number for every record. Wouldn't it be simpler if the sequence number was calculated by payment_dta internally and the caller does not need to care? Are there reasons not to implement the automatic numbering?

**Comment by phuesler** [comment]
I don't think the payment should know anything about the data file it lives in. Agreed, the code is not very clear. You don't have to pass in the output sequence number, DTAFile#<< method does this by calling DTAFile#recalculate_output_sequence_numbers.  Granted, this code is not very efficient, because it recalculates the sequence numbers every time a record is appended.

**Comment by senny** [comment]
I think it was a misunderstanding of terms. I've seen that you calculate the `output_sequence_number` and I totally agree that this code should live outside of the payment implementations. The problem is, that according to the specification the `output_sequence_number` is a constant of '00000' and does not need any calculation. The `entry_sequence_number` however must be unique in a given DTA-File and this number currently needs to be set when creating a payment... So I think we should repoen this issue since the calculation happens on the wrong field.
